services:
  nginx:
    image: nginx:latest
    container_name: service-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_1
      - app_2
      - app_3
    networks:
      - my_network

  app_1:
    build: .
    container_name: myapp-1
    expose:
      - "8080"
    networks:
      - my_network

  app_2:
    build: .
    container_name: myapp-2
    expose:
      - "8080"
    networks:
      - my_network
      
  app_3:
    build: .
    container_name: myapp-3
    expose:
      - "8080"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
